name: single_story_album
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  widgets_to_image: ^0.0.2
  image_gallery_saver: ^2.0.3
  http: ^1.1.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  fluttertoast: ^8.2.2
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  widget_zoom: ^0.0.2
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/add_image.png
  uses-material-design: true


flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/photo-album.png"
  min_sdk_android: 19
  remove_alpha_ios: true